# Generated by Django 5.0.6 on 2024-06-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="problemm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_name", models.CharField(max_length=100)),
                ("problem_description", models.CharField(max_length=500)),
                ("problem_input", models.TextField()),
                ("problem_code", models.CharField(max_length=200)),
                ("problem_diff", models.CharField(max_length=200)),
            ],
        ),
    ]
