# Generated by Django 5.0.6 on 2024-06-27 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("porblems", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problemm",
            name="problem_code",
        ),
        migrations.RemoveField(
            model_name="problemm",
            name="problem_input",
        ),
        migrations.AlterField(
            model_name="problemm",
            name="problem_description",
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name="solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verdict", models.CharField(max_length=200)),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="porblems.problemm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Test_Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Input", models.CharField(max_length=5000)),
                ("Output", models.CharField(max_length=5000)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="porblems.problemm",
                    ),
                ),
            ],
        ),
    ]
