# Generated by Django 5.0.6 on 2024-06-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("porblems", "0002_remove_problemm_problem_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemm",
            name="problem_input",
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name="problemm",
            name="problem_output",
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
