# Generated by Django 5.0.6 on 2024-06-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("porblems", "0003_problemm_problem_input_problemm_problem_output"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemm",
            name="problem_input",
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name="problemm",
            name="problem_output",
            field=models.TextField(default=0),
        ),
    ]
